### ISSUE TITLE
v2 links not works

### ISSUE THREAD

**Issue by whoizit** [vandadnp/flashcards#2]
403, 404

**Comment by vandadnp** [comment]
They should be working now. Please try again

**Comment by whoizit** [comment]
_Print_ link still 404

**Comment by vandadnp** [comment]
fixed that now too, thank you. Could you test again please?

**Comment by whoizit** [comment]
everything works for me, thank you very much!

**Comment by vandadnp** [comment]
Thank you for taking the time to bring this to my attention
